require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EncuestaController do

  # This should return the minimal set of attributes required to create a valid
  # Encuestum. As you add validations to Encuestum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EncuestaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all encuesta as @encuesta" do
      encuestum = Encuestum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:encuesta).should eq([encuestum])
    end
  end

  describe "GET show" do
    it "assigns the requested encuestum as @encuestum" do
      encuestum = Encuestum.create! valid_attributes
      get :show, {:id => encuestum.to_param}, valid_session
      assigns(:encuestum).should eq(encuestum)
    end
  end

  describe "GET new" do
    it "assigns a new encuestum as @encuestum" do
      get :new, {}, valid_session
      assigns(:encuestum).should be_a_new(Encuestum)
    end
  end

  describe "GET edit" do
    it "assigns the requested encuestum as @encuestum" do
      encuestum = Encuestum.create! valid_attributes
      get :edit, {:id => encuestum.to_param}, valid_session
      assigns(:encuestum).should eq(encuestum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Encuestum" do
        expect {
          post :create, {:encuestum => valid_attributes}, valid_session
        }.to change(Encuestum, :count).by(1)
      end

      it "assigns a newly created encuestum as @encuestum" do
        post :create, {:encuestum => valid_attributes}, valid_session
        assigns(:encuestum).should be_a(Encuestum)
        assigns(:encuestum).should be_persisted
      end

      it "redirects to the created encuestum" do
        post :create, {:encuestum => valid_attributes}, valid_session
        response.should redirect_to(Encuestum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved encuestum as @encuestum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encuestum.any_instance.stub(:save).and_return(false)
        post :create, {:encuestum => {}}, valid_session
        assigns(:encuestum).should be_a_new(Encuestum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encuestum.any_instance.stub(:save).and_return(false)
        post :create, {:encuestum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested encuestum" do
        encuestum = Encuestum.create! valid_attributes
        # Assuming there are no other encuesta in the database, this
        # specifies that the Encuestum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Encuestum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => encuestum.to_param, :encuestum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested encuestum as @encuestum" do
        encuestum = Encuestum.create! valid_attributes
        put :update, {:id => encuestum.to_param, :encuestum => valid_attributes}, valid_session
        assigns(:encuestum).should eq(encuestum)
      end

      it "redirects to the encuestum" do
        encuestum = Encuestum.create! valid_attributes
        put :update, {:id => encuestum.to_param, :encuestum => valid_attributes}, valid_session
        response.should redirect_to(encuestum)
      end
    end

    describe "with invalid params" do
      it "assigns the encuestum as @encuestum" do
        encuestum = Encuestum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encuestum.any_instance.stub(:save).and_return(false)
        put :update, {:id => encuestum.to_param, :encuestum => {}}, valid_session
        assigns(:encuestum).should eq(encuestum)
      end

      it "re-renders the 'edit' template" do
        encuestum = Encuestum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encuestum.any_instance.stub(:save).and_return(false)
        put :update, {:id => encuestum.to_param, :encuestum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested encuestum" do
      encuestum = Encuestum.create! valid_attributes
      expect {
        delete :destroy, {:id => encuestum.to_param}, valid_session
      }.to change(Encuestum, :count).by(-1)
    end

    it "redirects to the encuesta list" do
      encuestum = Encuestum.create! valid_attributes
      delete :destroy, {:id => encuestum.to_param}, valid_session
      response.should redirect_to(encuesta_url)
    end
  end

end
