require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MaestriaController do

  # This should return the minimal set of attributes required to create a valid
  # Maestrium. As you add validations to Maestrium, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MaestriaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all maestria as @maestria" do
      maestrium = Maestrium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:maestria).should eq([maestrium])
    end
  end

  describe "GET show" do
    it "assigns the requested maestrium as @maestrium" do
      maestrium = Maestrium.create! valid_attributes
      get :show, {:id => maestrium.to_param}, valid_session
      assigns(:maestrium).should eq(maestrium)
    end
  end

  describe "GET new" do
    it "assigns a new maestrium as @maestrium" do
      get :new, {}, valid_session
      assigns(:maestrium).should be_a_new(Maestrium)
    end
  end

  describe "GET edit" do
    it "assigns the requested maestrium as @maestrium" do
      maestrium = Maestrium.create! valid_attributes
      get :edit, {:id => maestrium.to_param}, valid_session
      assigns(:maestrium).should eq(maestrium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Maestrium" do
        expect {
          post :create, {:maestrium => valid_attributes}, valid_session
        }.to change(Maestrium, :count).by(1)
      end

      it "assigns a newly created maestrium as @maestrium" do
        post :create, {:maestrium => valid_attributes}, valid_session
        assigns(:maestrium).should be_a(Maestrium)
        assigns(:maestrium).should be_persisted
      end

      it "redirects to the created maestrium" do
        post :create, {:maestrium => valid_attributes}, valid_session
        response.should redirect_to(Maestrium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved maestrium as @maestrium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Maestrium.any_instance.stub(:save).and_return(false)
        post :create, {:maestrium => {}}, valid_session
        assigns(:maestrium).should be_a_new(Maestrium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Maestrium.any_instance.stub(:save).and_return(false)
        post :create, {:maestrium => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested maestrium" do
        maestrium = Maestrium.create! valid_attributes
        # Assuming there are no other maestria in the database, this
        # specifies that the Maestrium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Maestrium.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => maestrium.to_param, :maestrium => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested maestrium as @maestrium" do
        maestrium = Maestrium.create! valid_attributes
        put :update, {:id => maestrium.to_param, :maestrium => valid_attributes}, valid_session
        assigns(:maestrium).should eq(maestrium)
      end

      it "redirects to the maestrium" do
        maestrium = Maestrium.create! valid_attributes
        put :update, {:id => maestrium.to_param, :maestrium => valid_attributes}, valid_session
        response.should redirect_to(maestrium)
      end
    end

    describe "with invalid params" do
      it "assigns the maestrium as @maestrium" do
        maestrium = Maestrium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Maestrium.any_instance.stub(:save).and_return(false)
        put :update, {:id => maestrium.to_param, :maestrium => {}}, valid_session
        assigns(:maestrium).should eq(maestrium)
      end

      it "re-renders the 'edit' template" do
        maestrium = Maestrium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Maestrium.any_instance.stub(:save).and_return(false)
        put :update, {:id => maestrium.to_param, :maestrium => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested maestrium" do
      maestrium = Maestrium.create! valid_attributes
      expect {
        delete :destroy, {:id => maestrium.to_param}, valid_session
      }.to change(Maestrium, :count).by(-1)
    end

    it "redirects to the maestria list" do
      maestrium = Maestrium.create! valid_attributes
      delete :destroy, {:id => maestrium.to_param}, valid_session
      response.should redirect_to(maestria_url)
    end
  end

end
