require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MateriaTipoPensumsController do

  # This should return the minimal set of attributes required to create a valid
  # MateriaTipoPensum. As you add validations to MateriaTipoPensum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MateriaTipoPensumsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all materia_tipo_pensums as @materia_tipo_pensums" do
      materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:materia_tipo_pensums).should eq([materia_tipo_pensum])
    end
  end

  describe "GET show" do
    it "assigns the requested materia_tipo_pensum as @materia_tipo_pensum" do
      materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
      get :show, {:id => materia_tipo_pensum.to_param}, valid_session
      assigns(:materia_tipo_pensum).should eq(materia_tipo_pensum)
    end
  end

  describe "GET new" do
    it "assigns a new materia_tipo_pensum as @materia_tipo_pensum" do
      get :new, {}, valid_session
      assigns(:materia_tipo_pensum).should be_a_new(MateriaTipoPensum)
    end
  end

  describe "GET edit" do
    it "assigns the requested materia_tipo_pensum as @materia_tipo_pensum" do
      materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
      get :edit, {:id => materia_tipo_pensum.to_param}, valid_session
      assigns(:materia_tipo_pensum).should eq(materia_tipo_pensum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MateriaTipoPensum" do
        expect {
          post :create, {:materia_tipo_pensum => valid_attributes}, valid_session
        }.to change(MateriaTipoPensum, :count).by(1)
      end

      it "assigns a newly created materia_tipo_pensum as @materia_tipo_pensum" do
        post :create, {:materia_tipo_pensum => valid_attributes}, valid_session
        assigns(:materia_tipo_pensum).should be_a(MateriaTipoPensum)
        assigns(:materia_tipo_pensum).should be_persisted
      end

      it "redirects to the created materia_tipo_pensum" do
        post :create, {:materia_tipo_pensum => valid_attributes}, valid_session
        response.should redirect_to(MateriaTipoPensum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved materia_tipo_pensum as @materia_tipo_pensum" do
        # Trigger the behavior that occurs when invalid params are submitted
        MateriaTipoPensum.any_instance.stub(:save).and_return(false)
        post :create, {:materia_tipo_pensum => {}}, valid_session
        assigns(:materia_tipo_pensum).should be_a_new(MateriaTipoPensum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MateriaTipoPensum.any_instance.stub(:save).and_return(false)
        post :create, {:materia_tipo_pensum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested materia_tipo_pensum" do
        materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
        # Assuming there are no other materia_tipo_pensums in the database, this
        # specifies that the MateriaTipoPensum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MateriaTipoPensum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => materia_tipo_pensum.to_param, :materia_tipo_pensum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested materia_tipo_pensum as @materia_tipo_pensum" do
        materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
        put :update, {:id => materia_tipo_pensum.to_param, :materia_tipo_pensum => valid_attributes}, valid_session
        assigns(:materia_tipo_pensum).should eq(materia_tipo_pensum)
      end

      it "redirects to the materia_tipo_pensum" do
        materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
        put :update, {:id => materia_tipo_pensum.to_param, :materia_tipo_pensum => valid_attributes}, valid_session
        response.should redirect_to(materia_tipo_pensum)
      end
    end

    describe "with invalid params" do
      it "assigns the materia_tipo_pensum as @materia_tipo_pensum" do
        materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MateriaTipoPensum.any_instance.stub(:save).and_return(false)
        put :update, {:id => materia_tipo_pensum.to_param, :materia_tipo_pensum => {}}, valid_session
        assigns(:materia_tipo_pensum).should eq(materia_tipo_pensum)
      end

      it "re-renders the 'edit' template" do
        materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MateriaTipoPensum.any_instance.stub(:save).and_return(false)
        put :update, {:id => materia_tipo_pensum.to_param, :materia_tipo_pensum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested materia_tipo_pensum" do
      materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
      expect {
        delete :destroy, {:id => materia_tipo_pensum.to_param}, valid_session
      }.to change(MateriaTipoPensum, :count).by(-1)
    end

    it "redirects to the materia_tipo_pensums list" do
      materia_tipo_pensum = MateriaTipoPensum.create! valid_attributes
      delete :destroy, {:id => materia_tipo_pensum.to_param}, valid_session
      response.should redirect_to(materia_tipo_pensums_url)
    end
  end

end
