require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PeriodosController do

  # This should return the minimal set of attributes required to create a valid
  # Periodo. As you add validations to Periodo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PeriodosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all periodos as @periodos" do
      periodo = Periodo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:periodos).should eq([periodo])
    end
  end

  describe "GET show" do
    it "assigns the requested periodo as @periodo" do
      periodo = Periodo.create! valid_attributes
      get :show, {:id => periodo.to_param}, valid_session
      assigns(:periodo).should eq(periodo)
    end
  end

  describe "GET new" do
    it "assigns a new periodo as @periodo" do
      get :new, {}, valid_session
      assigns(:periodo).should be_a_new(Periodo)
    end
  end

  describe "GET edit" do
    it "assigns the requested periodo as @periodo" do
      periodo = Periodo.create! valid_attributes
      get :edit, {:id => periodo.to_param}, valid_session
      assigns(:periodo).should eq(periodo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Periodo" do
        expect {
          post :create, {:periodo => valid_attributes}, valid_session
        }.to change(Periodo, :count).by(1)
      end

      it "assigns a newly created periodo as @periodo" do
        post :create, {:periodo => valid_attributes}, valid_session
        assigns(:periodo).should be_a(Periodo)
        assigns(:periodo).should be_persisted
      end

      it "redirects to the created periodo" do
        post :create, {:periodo => valid_attributes}, valid_session
        response.should redirect_to(Periodo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved periodo as @periodo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Periodo.any_instance.stub(:save).and_return(false)
        post :create, {:periodo => {}}, valid_session
        assigns(:periodo).should be_a_new(Periodo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Periodo.any_instance.stub(:save).and_return(false)
        post :create, {:periodo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested periodo" do
        periodo = Periodo.create! valid_attributes
        # Assuming there are no other periodos in the database, this
        # specifies that the Periodo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Periodo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => periodo.to_param, :periodo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested periodo as @periodo" do
        periodo = Periodo.create! valid_attributes
        put :update, {:id => periodo.to_param, :periodo => valid_attributes}, valid_session
        assigns(:periodo).should eq(periodo)
      end

      it "redirects to the periodo" do
        periodo = Periodo.create! valid_attributes
        put :update, {:id => periodo.to_param, :periodo => valid_attributes}, valid_session
        response.should redirect_to(periodo)
      end
    end

    describe "with invalid params" do
      it "assigns the periodo as @periodo" do
        periodo = Periodo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Periodo.any_instance.stub(:save).and_return(false)
        put :update, {:id => periodo.to_param, :periodo => {}}, valid_session
        assigns(:periodo).should eq(periodo)
      end

      it "re-renders the 'edit' template" do
        periodo = Periodo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Periodo.any_instance.stub(:save).and_return(false)
        put :update, {:id => periodo.to_param, :periodo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested periodo" do
      periodo = Periodo.create! valid_attributes
      expect {
        delete :destroy, {:id => periodo.to_param}, valid_session
      }.to change(Periodo, :count).by(-1)
    end

    it "redirects to the periodos list" do
      periodo = Periodo.create! valid_attributes
      delete :destroy, {:id => periodo.to_param}, valid_session
      response.should redirect_to(periodos_url)
    end
  end

end
